export const categories = [
  "Smartphones",
  "Laptops",
  "Tablets",
  "Desktop Computers",
  "Smartwatches",
  "Televisions",
  "Home Audio Systems",
  "Gaming Consoles",
  "Digital Cameras",
  "Headphones & Earbuds",
  "Smart Home Devices",
  "Wearable Fitness Trackers",
  "E-Readers",
];
